/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Content/Alert.vue')['default']
    AutoComplete: typeof import('./src/components/Input/AutoComplete.vue')['default']
    Badge: typeof import('./src/components/Content/Badge.vue')['default']
    BaseForm: typeof import('./src/components/Forms/BaseForm.vue')['default']
    BaseIcon: typeof import('./src/components/UI/BaseIcon.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    Button: typeof import('./src/components/UI/Button.vue')['default']
    Checkbox: typeof import('./src/components/Input/Checkbox.vue')['default']
    CommunalPlan: typeof import('./src/components/Layers/CommunalPlan.vue')['default']
    Competitors: typeof import('./src/components/Layers/Competitors.vue')['default']
    Corridors: typeof import('./src/components/Layers/Corridors.vue')['default']
    CustomSelect: typeof import('./src/components/Input/CustomSelect.vue')['default']
    DatePicker: typeof import('./src/components/Input/DatePicker.vue')['default']
    DeleteModal: typeof import('./src/components/DeleteModal.vue')['default']
    Density: typeof import('./src/components/Layers/Density.vue')['default']
    Divider: typeof import('./src/components/UI/Divider.vue')['default']
    Footer: typeof import('./src/components/UI/Footer.vue')['default']
    InputValidateField: typeof import('./src/components/Input/InputValidateField.vue')['default']
    Lands: typeof import('./src/components/Layers/Lands.vue')['default']
    LoginBox: typeof import('./src/components/Forms/LoginBox.vue')['default']
    MainForm: typeof import('./src/components/MainForm.vue')['default']
    Megacenters: typeof import('./src/components/Layers/Megacenters.vue')['default']
    MetropolitanPlan: typeof import('./src/components/Layers/MetropolitanPlan.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Poles: typeof import('./src/components/Layers/Poles.vue')['default']
    RadioButtons: typeof import('./src/components/Input/RadioButtons.vue')['default']
    Roads: typeof import('./src/components/Layers/Roads.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Input/Select.vue')['default']
    SelectMultiple: typeof import('./src/components/Input/SelectMultiple.vue')['default']
    SelectOption: typeof import('./src/components/Input/SelectOption.vue')['default']
    Spinner: typeof import('./src/components/UI/Spinner.vue')['default']
    TextAreaField: typeof import('./src/components/Input/TextAreaField.vue')['default']
    TextField: typeof import('./src/components/Input/TextField.vue')['default']
    Toogle: typeof import('./src/components/Input/Toogle.vue')['default']
    UploadFile: typeof import('./src/components/Input/UploadFile.vue')['default']
    UploadModal: typeof import('./src/components/UploadModal.vue')['default']
    Warehouses: typeof import('./src/components/Layers/Warehouses.vue')['default']
  }
}
